#!/bin/sh

# Split into two steps for the case where HOME contains a copy of an existing
# file in $HOME and stow will not --restow because of conflicts

# First, adopt any real files that match the files in HOME
# since we've already committed our changes, if the adopted file differs git
# status will show that it's been modified
echo "Stowing HOME with --adopt option"
stow --adopt .

# Second, restow to prune any stale symlinks
echo "Stowing HOME with --restow option (to prune any stale symlinks)"
stow --restow .
