#!/bin/zsh
# Basic script to kill all old bars and launch new.
# Taken from https://github.com/jaagr/polybar/wiki

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
if [ "$HOST" = "yemen" ]; then
    polybar main &
else
    polybar mainA &
    polybar mainB &
fi

echo "Bars launched..."
