#!/bin/zsh
# Basic script to kill all old bars and launch new.
# Taken from https://github.com/jaagr/polybar/wiki

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 0.1; done

# Launch bar1 and bar2
if [ "$HOST" = "yemen" ]; then
    polybar main & disown
elif [ "$HOST" = "mongolia" ]; then
    polybar mainA & disown
    polybar mainB & disown
    polybar mainC & disown
fi

echo "Bars launched..."
