#!/usr/bin/env sh
# Taken from https://github.com/jaagr/polybar/wiki

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
polybar mainA &
polybar mainB &

echo "Bars launched..."
