#!/bin/sh
# Script modified from
# https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/openweathermap-fullfeatured
# 
# Icons at https://erikflowers.github.io/weather-icons/
get_icon() {
    case $1 in
        # Icons for Nerd Fonts
        # Glyphs are searchable here: https://www.nerdfonts.com/cheat-sheet
        01d) icon="  ";;  # \Ue30d  nf-weather-day_sunny
        01n) icon="  ";;  # \Ue32b  nf-weather-night_clear
        02d) icon="  ";;  # \Ue302  nf-weather-day_cloudy
        02n) icon="  ";;  # \Ue37e  nf-weather-night_alt_cloudy
        03*) icon="  ";;  # \Ue33d  nf-weather-cloud
        04*) icon="  ";;  # \Ue312  nf-weather-cloudy
        09*) icon="  ";;  # \Ue317  nf-weather-rain_wind
        10d) icon="  ";;  # \Ue308  nf-weather-day_rain
        10n) icon="  ";;  # \Ue333  nf-weather-night_rain
        11d) icon="  ";;  # \Ue305  nf-weather-day_lightning
        11n) icon="  ";;  # \Ue322  nf-weather-night_alt_lightning
        13d) icon="  ";;  # \Ue30a  nf-weather-day_snow
        13n) icon="  ";;  # \Ue327  nf-weather-night_alt_snow
        50d) icon="  ";;  # \Ue303  nf-weather-day_fog
        50n) icon="  ";;  # \Ue346  nf-weather-night_fog
        *)   icon="  ";   # \Uf128  nf-fa-question

        # Icons for weather-icons
        #01d) icon="";;  # \Uf00d  wi-day-sunny
        #01n) icon="";;  # \Uf02e  wi-night-clear
        #02d) icon="";;  # \Uf002  wi-day-cloudy
        #02n) icon="";;  # \Uf086  wi-night-alt-cloudy
        #03*) icon="";;  # \Uf041  wi-cloud
        #04*) icon="";;  # \Uf013  wi-cloudy
        #09d) icon="";;  # \Uf018  wi-rain-wind
        #09n) icon="";;  # \Uf018  wi-rain-wind
        #10d) icon="";;  # \Uf008  wi-day-rain
        #10n) icon="";;  # \Uf036  wi-night-rain
        #11d) icon="";;  # \Uf005  wi-day-lightning
        #11n) icon="";;  # \Uf025  wi-night-alt-lightning
        #13d) icon="";;  # \Uf00a  wi-day-snow
        #13n) icon="";;  # \Uf02a  wi-night-alt-snow
        #50d) icon="";;  # \Uf003  wi-day-fog
        #50n) icon="";;  # \Uf04a  wi-night-fog
        #*)   icon="";;  # \Uf00d  wi-day-sunny
    esac

    echo $icon
}

get_duration() {

    osname=$(uname -s)

    case $osname in
        *BSD) date -r "$1" -u +%H:%M;;
        *) date --date="@$1" -u +%H:%M;;
    esac

}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

KEY="`cat ${DIR}/weather_api_key`"
#CITY="King%20George"
#CITY=4767771
UNITS="imperial"
#SYMBOL="°"
#SYMBOL=""  # \Ue339 nf-weather-celsius
#SYMBOL="糖"  # \Ufa03 nf-mdi-temperature_celsius
#SYMBOL="°C"
SYMBOL="°F"

API="https://api.openweathermap.org/data/2.5"

if [ -n "$CITY" ]; then
    if [ "$CITY" -eq "$CITY" ] 2>/dev/null; then
        CITY_PARAM="id=$CITY"
    else
        CITY_PARAM="q=$CITY"
    fi

    current=$(curl -sf "$API/weather?appid=$KEY&$CITY_PARAM&units=$UNITS")
    forecast=$(curl -sf "$API/forecast?appid=$KEY&$CITY_PARAM&units=$UNITS&cnt=1")
else
    location=$(curl -sf https://location.services.mozilla.com/v1/geolocate?key=geoclue)

    if [ -n "$location" ]; then
        location_lat="$(echo "$location" | jq '.location.lat')"
        location_lon="$(echo "$location" | jq '.location.lng')"

        current=$(curl -sf "$API/weather?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS")
        forecast=$(curl -sf "$API/forecast?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS&cnt=1")
    fi
fi

if [ -n "$current" ] && [ -n "$forecast" ]; then
    current_temp=$(echo "$current" | jq ".main.temp" | cut -d "." -f 1)
    current_icon=$(echo "$current" | jq -r ".weather[0].icon")

    forecast_temp=$(echo "$forecast" | jq ".list[].main.temp" | cut -d "." -f 1)
    forecast_icon=$(echo "$forecast" | jq -r ".list[].weather[0].icon")

    if [ "$current_temp" -gt "$forecast_temp" ]; then
        trend=""  # \Ue380  nf-weather-direction_down_right
        #trend=""  # \Uf088  wi-direction-down-right
    elif [ "$forecast_temp" -gt "$current_temp" ]; then
        trend=""  # \Ue352  nf-weather-direction_up_right
        #trend=""  # \Uf057  wi-direction-up-right
    else
        trend=""  # \Ue349  nf-weather-direction_right
        #trend=""  # \Uf04d  wi-direction-right
    fi

    sun_rise=$(echo "$current" | jq ".sys.sunrise")
    sun_set=$(echo "$current" | jq ".sys.sunset")
    now=$(date +%s)

    if [ "$sun_rise" -gt "$now" ]; then
        daytime="    $(get_duration "$((sun_rise-now))")"  # \Ue34c  nf-weather-sunrise
        #daytime="   $(get_duration "$((sun_rise-now))")"  # \Uf051  wi-sunrise
    elif [ "$sun_set" -gt "$now" ]; then
        daytime="    $(get_duration "$((sun_set-now))")"  # \Ue34d  nf-weather-sunset
        #daytime="   $(get_duration "$((sun_set-now))")"  # \Uf052  wi-sunset 
    else
        daytime="    $(get_duration "$((sun_rise-now))")"  # \Ue34c  nf-weather-sunrise
        #daytime="   $(get_duration "$((sun_rise-now))")"  # \Uf051  wi-sunrise
    fi

    echo "$(get_icon "$current_icon")    $current_temp$SYMBOL  $trend  $(get_icon "$forecast_icon")    $forecast_temp$SYMBOL   $daytime"
fi
